/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 50
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_text_token1 = 1,
  sym_arg_text = 2,
  sym_escaped_special = 3,
  anon_sym_PERCENT_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_LPAREN = 6,
  sym_macro_name = 7,
  anon_sym_COMMA = 8,
  sym_block_open = 9,
  sym_block_close = 10,
  sym_line_comment = 11,
  anon_sym_PERCENT_SLASH_STAR = 12,
  aux_sym_block_comment_token1 = 13,
  anon_sym_PERCENT_STAR_SLASH = 14,
  sym_identifier = 15,
  sym_source_file = 16,
  sym__node = 17,
  sym__arg_node = 18,
  sym_text = 19,
  sym_variable = 20,
  sym_macro_call = 21,
  sym__arg_list = 22,
  sym_argument = 23,
  sym_block = 24,
  sym_block_comment = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym__arg_list_repeat1 = 27,
  aux_sym_argument_repeat1 = 28,
  aux_sym_block_comment_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_text_token1] = "text_token1",
  [sym_arg_text] = "arg_text",
  [sym_escaped_special] = "escaped_special",
  [anon_sym_PERCENT_LPAREN] = "%(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LPAREN] = "(",
  [sym_macro_name] = "macro_name",
  [anon_sym_COMMA] = ",",
  [sym_block_open] = "block_open",
  [sym_block_close] = "block_close",
  [sym_line_comment] = "line_comment",
  [anon_sym_PERCENT_SLASH_STAR] = "%/*",
  [aux_sym_block_comment_token1] = "block_comment_token1",
  [anon_sym_PERCENT_STAR_SLASH] = "%*/",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__node] = "_node",
  [sym__arg_node] = "_arg_node",
  [sym_text] = "text",
  [sym_variable] = "variable",
  [sym_macro_call] = "macro_call",
  [sym__arg_list] = "_arg_list",
  [sym_argument] = "argument",
  [sym_block] = "block",
  [sym_block_comment] = "block_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__arg_list_repeat1] = "_arg_list_repeat1",
  [aux_sym_argument_repeat1] = "argument_repeat1",
  [aux_sym_block_comment_repeat1] = "block_comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_text_token1] = aux_sym_text_token1,
  [sym_arg_text] = sym_arg_text,
  [sym_escaped_special] = sym_escaped_special,
  [anon_sym_PERCENT_LPAREN] = anon_sym_PERCENT_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [sym_macro_name] = sym_macro_name,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_block_open] = sym_block_open,
  [sym_block_close] = sym_block_close,
  [sym_line_comment] = sym_line_comment,
  [anon_sym_PERCENT_SLASH_STAR] = anon_sym_PERCENT_SLASH_STAR,
  [aux_sym_block_comment_token1] = aux_sym_block_comment_token1,
  [anon_sym_PERCENT_STAR_SLASH] = anon_sym_PERCENT_STAR_SLASH,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__node] = sym__node,
  [sym__arg_node] = sym__arg_node,
  [sym_text] = sym_text,
  [sym_variable] = sym_variable,
  [sym_macro_call] = sym_macro_call,
  [sym__arg_list] = sym__arg_list,
  [sym_argument] = sym_argument,
  [sym_block] = sym_block,
  [sym_block_comment] = sym_block_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__arg_list_repeat1] = aux_sym__arg_list_repeat1,
  [aux_sym_argument_repeat1] = aux_sym_argument_repeat1,
  [aux_sym_block_comment_repeat1] = aux_sym_block_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_text_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_arg_text] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped_special] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_macro_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_block_open] = {
    .visible = true,
    .named = true,
  },
  [sym_block_close] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym__arg_node] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_call] = {
    .visible = true,
    .named = true,
  },
  [sym__arg_list] = {
    .visible = false,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__arg_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg = 1,
  field_close = 2,
  field_name = 3,
  field_open = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg] = "arg",
  [field_close] = "close",
  [field_name] = "name",
  [field_open] = "open",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_close, 1},
    {field_open, 0},
  [2] =
    {field_name, 1},
  [3] =
    {field_name, 0},
  [4] =
    {field_arg, 0},
  [5] =
    {field_close, 2},
    {field_open, 0},
  [7] =
    {field_arg, 2, .inherited = true},
    {field_name, 0},
  [9] =
    {field_arg, 0},
    {field_arg, 1, .inherited = true},
  [11] =
    {field_arg, 1},
  [12] =
    {field_arg, 0, .inherited = true},
    {field_arg, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 9,
  [10] = 8,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 14,
  [20] = 20,
  [21] = 16,
  [22] = 17,
  [23] = 18,
  [24] = 13,
  [25] = 20,
  [26] = 15,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 29,
  [32] = 29,
  [33] = 30,
  [34] = 30,
  [35] = 13,
  [36] = 20,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 42,
  [47] = 45,
  [48] = 43,
  [49] = 41,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == '%') ADVANCE(3);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == ',') ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '}') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '{') ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == '*') ADVANCE(10);
      if (lookahead == '/') ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(2);
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == '%') ADVANCE(6);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(10);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(28);
      if (lookahead == '/') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(30);
      END_STATE();
    case 11:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '%') ADVANCE(1);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_arg_text);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '%' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_arg_text);
      if (lookahead != 0 &&
          lookahead != '%' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_escaped_special);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_PERCENT_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '}') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == '{') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_macro_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_block_open);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_block_close);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PERCENT_SLASH_STAR);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_block_comment_token1);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PERCENT_STAR_SLASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 11},
  [49] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_arg_text] = ACTIONS(1),
    [sym_escaped_special] = ACTIONS(1),
    [anon_sym_PERCENT_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [sym_macro_name] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PERCENT_SLASH_STAR] = ACTIONS(1),
    [aux_sym_block_comment_token1] = ACTIONS(1),
    [anon_sym_PERCENT_STAR_SLASH] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(44),
    [sym__node] = STATE(5),
    [sym_text] = STATE(5),
    [sym_variable] = STATE(5),
    [sym_macro_call] = STATE(5),
    [sym_block] = STATE(5),
    [sym_block_comment] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_text_token1] = ACTIONS(5),
    [sym_escaped_special] = ACTIONS(7),
    [anon_sym_PERCENT_LPAREN] = ACTIONS(9),
    [sym_macro_name] = ACTIONS(11),
    [sym_block_open] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(7),
    [anon_sym_PERCENT_SLASH_STAR] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym__arg_node] = STATE(9),
    [sym_variable] = STATE(9),
    [sym_macro_call] = STATE(9),
    [sym__arg_list] = STATE(47),
    [sym_argument] = STATE(39),
    [sym_block] = STATE(9),
    [sym_block_comment] = STATE(9),
    [aux_sym_argument_repeat1] = STATE(9),
    [sym_arg_text] = ACTIONS(17),
    [sym_escaped_special] = ACTIONS(17),
    [anon_sym_PERCENT_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(21),
    [sym_macro_name] = ACTIONS(23),
    [sym_block_open] = ACTIONS(25),
    [sym_line_comment] = ACTIONS(17),
    [anon_sym_PERCENT_SLASH_STAR] = ACTIONS(27),
  },
  [STATE(3)] = {
    [sym__arg_node] = STATE(9),
    [sym_variable] = STATE(9),
    [sym_macro_call] = STATE(9),
    [sym__arg_list] = STATE(45),
    [sym_argument] = STATE(39),
    [sym_block] = STATE(9),
    [sym_block_comment] = STATE(9),
    [aux_sym_argument_repeat1] = STATE(9),
    [sym_arg_text] = ACTIONS(17),
    [sym_escaped_special] = ACTIONS(17),
    [anon_sym_PERCENT_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(29),
    [sym_macro_name] = ACTIONS(23),
    [sym_block_open] = ACTIONS(25),
    [sym_line_comment] = ACTIONS(17),
    [anon_sym_PERCENT_SLASH_STAR] = ACTIONS(27),
  },
  [STATE(4)] = {
    [sym__node] = STATE(4),
    [sym_text] = STATE(4),
    [sym_variable] = STATE(4),
    [sym_macro_call] = STATE(4),
    [sym_block] = STATE(4),
    [sym_block_comment] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(31),
    [aux_sym_text_token1] = ACTIONS(33),
    [sym_escaped_special] = ACTIONS(36),
    [anon_sym_PERCENT_LPAREN] = ACTIONS(39),
    [sym_macro_name] = ACTIONS(42),
    [sym_block_open] = ACTIONS(45),
    [sym_block_close] = ACTIONS(31),
    [sym_line_comment] = ACTIONS(36),
    [anon_sym_PERCENT_SLASH_STAR] = ACTIONS(48),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      aux_sym_text_token1,
    ACTIONS(9), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(11), 1,
      sym_macro_name,
    ACTIONS(13), 1,
      sym_block_open,
    ACTIONS(15), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 2,
      sym_escaped_special,
      sym_line_comment,
    STATE(4), 7,
      sym__node,
      sym_text,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_block_comment,
      aux_sym_source_file_repeat1,
  [32] = 8,
    ACTIONS(5), 1,
      aux_sym_text_token1,
    ACTIONS(9), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(11), 1,
      sym_macro_name,
    ACTIONS(13), 1,
      sym_block_open,
    ACTIONS(15), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(55), 1,
      sym_block_close,
    ACTIONS(53), 2,
      sym_escaped_special,
      sym_line_comment,
    STATE(4), 7,
      sym__node,
      sym_text,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_block_comment,
      aux_sym_source_file_repeat1,
  [64] = 8,
    ACTIONS(5), 1,
      aux_sym_text_token1,
    ACTIONS(9), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(11), 1,
      sym_macro_name,
    ACTIONS(13), 1,
      sym_block_open,
    ACTIONS(15), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(57), 1,
      sym_block_close,
    ACTIONS(53), 2,
      sym_escaped_special,
      sym_line_comment,
    STATE(4), 7,
      sym__node,
      sym_text,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_block_comment,
      aux_sym_source_file_repeat1,
  [96] = 8,
    ACTIONS(5), 1,
      aux_sym_text_token1,
    ACTIONS(9), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(11), 1,
      sym_macro_name,
    ACTIONS(13), 1,
      sym_block_open,
    ACTIONS(15), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(61), 1,
      sym_block_close,
    ACTIONS(59), 2,
      sym_escaped_special,
      sym_line_comment,
    STATE(7), 7,
      sym__node,
      sym_text,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_block_comment,
      aux_sym_source_file_repeat1,
  [128] = 7,
    ACTIONS(19), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(23), 1,
      sym_macro_name,
    ACTIONS(25), 1,
      sym_block_open,
    ACTIONS(27), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(65), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(63), 3,
      sym_arg_text,
      sym_escaped_special,
      sym_line_comment,
    STATE(11), 6,
      sym__arg_node,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_block_comment,
      aux_sym_argument_repeat1,
  [158] = 8,
    ACTIONS(5), 1,
      aux_sym_text_token1,
    ACTIONS(9), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(11), 1,
      sym_macro_name,
    ACTIONS(13), 1,
      sym_block_open,
    ACTIONS(15), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(69), 1,
      sym_block_close,
    ACTIONS(67), 2,
      sym_escaped_special,
      sym_line_comment,
    STATE(6), 7,
      sym__node,
      sym_text,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_block_comment,
      aux_sym_source_file_repeat1,
  [190] = 7,
    ACTIONS(74), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(79), 1,
      sym_macro_name,
    ACTIONS(82), 1,
      sym_block_open,
    ACTIONS(85), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(77), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(71), 3,
      sym_arg_text,
      sym_escaped_special,
      sym_line_comment,
    STATE(11), 6,
      sym__arg_node,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_block_comment,
      aux_sym_argument_repeat1,
  [220] = 7,
    ACTIONS(19), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(23), 1,
      sym_macro_name,
    ACTIONS(25), 1,
      sym_block_open,
    ACTIONS(27), 1,
      anon_sym_PERCENT_SLASH_STAR,
    STATE(40), 1,
      sym_argument,
    ACTIONS(17), 3,
      sym_arg_text,
      sym_escaped_special,
      sym_line_comment,
    STATE(9), 6,
      sym__arg_node,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_block_comment,
      aux_sym_argument_repeat1,
  [249] = 2,
    ACTIONS(90), 1,
      sym_macro_name,
    ACTIONS(88), 8,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [263] = 2,
    ACTIONS(94), 1,
      sym_macro_name,
    ACTIONS(92), 8,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [277] = 2,
    ACTIONS(98), 1,
      sym_macro_name,
    ACTIONS(96), 8,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [291] = 2,
    ACTIONS(102), 1,
      sym_macro_name,
    ACTIONS(100), 8,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [305] = 2,
    ACTIONS(106), 1,
      sym_macro_name,
    ACTIONS(104), 8,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [319] = 2,
    ACTIONS(110), 1,
      sym_macro_name,
    ACTIONS(108), 8,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [333] = 2,
    ACTIONS(94), 1,
      sym_macro_name,
    ACTIONS(92), 8,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [347] = 2,
    ACTIONS(114), 1,
      sym_macro_name,
    ACTIONS(112), 8,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [361] = 2,
    ACTIONS(102), 1,
      sym_macro_name,
    ACTIONS(100), 8,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [375] = 2,
    ACTIONS(106), 1,
      sym_macro_name,
    ACTIONS(104), 8,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [389] = 2,
    ACTIONS(110), 1,
      sym_macro_name,
    ACTIONS(108), 8,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [403] = 2,
    ACTIONS(90), 1,
      sym_macro_name,
    ACTIONS(88), 8,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [417] = 2,
    ACTIONS(114), 1,
      sym_macro_name,
    ACTIONS(112), 8,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [431] = 2,
    ACTIONS(98), 1,
      sym_macro_name,
    ACTIONS(96), 8,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [445] = 2,
    ACTIONS(118), 1,
      sym_macro_name,
    ACTIONS(116), 8,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [459] = 4,
    ACTIONS(123), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(126), 1,
      anon_sym_PERCENT_STAR_SLASH,
    ACTIONS(120), 2,
      aux_sym_text_token1,
      aux_sym_block_comment_token1,
    STATE(28), 2,
      sym_block_comment,
      aux_sym_block_comment_repeat1,
  [474] = 4,
    ACTIONS(130), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(132), 1,
      anon_sym_PERCENT_STAR_SLASH,
    ACTIONS(128), 2,
      aux_sym_text_token1,
      aux_sym_block_comment_token1,
    STATE(30), 2,
      sym_block_comment,
      aux_sym_block_comment_repeat1,
  [489] = 4,
    ACTIONS(130), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(136), 1,
      anon_sym_PERCENT_STAR_SLASH,
    ACTIONS(134), 2,
      aux_sym_text_token1,
      aux_sym_block_comment_token1,
    STATE(28), 2,
      sym_block_comment,
      aux_sym_block_comment_repeat1,
  [504] = 4,
    ACTIONS(130), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(140), 1,
      anon_sym_PERCENT_STAR_SLASH,
    ACTIONS(138), 2,
      aux_sym_text_token1,
      aux_sym_block_comment_token1,
    STATE(34), 2,
      sym_block_comment,
      aux_sym_block_comment_repeat1,
  [519] = 4,
    ACTIONS(130), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(144), 1,
      anon_sym_PERCENT_STAR_SLASH,
    ACTIONS(142), 2,
      aux_sym_text_token1,
      aux_sym_block_comment_token1,
    STATE(33), 2,
      sym_block_comment,
      aux_sym_block_comment_repeat1,
  [534] = 4,
    ACTIONS(130), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(146), 1,
      anon_sym_PERCENT_STAR_SLASH,
    ACTIONS(134), 2,
      aux_sym_text_token1,
      aux_sym_block_comment_token1,
    STATE(28), 2,
      sym_block_comment,
      aux_sym_block_comment_repeat1,
  [549] = 4,
    ACTIONS(130), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(148), 1,
      anon_sym_PERCENT_STAR_SLASH,
    ACTIONS(134), 2,
      aux_sym_text_token1,
      aux_sym_block_comment_token1,
    STATE(28), 2,
      sym_block_comment,
      aux_sym_block_comment_repeat1,
  [564] = 1,
    ACTIONS(88), 4,
      aux_sym_text_token1,
      anon_sym_PERCENT_SLASH_STAR,
      aux_sym_block_comment_token1,
      anon_sym_PERCENT_STAR_SLASH,
  [571] = 1,
    ACTIONS(112), 4,
      aux_sym_text_token1,
      anon_sym_PERCENT_SLASH_STAR,
      aux_sym_block_comment_token1,
      anon_sym_PERCENT_STAR_SLASH,
  [578] = 3,
    ACTIONS(150), 1,
      anon_sym_RPAREN,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    STATE(38), 1,
      aux_sym__arg_list_repeat1,
  [588] = 3,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    STATE(38), 1,
      aux_sym__arg_list_repeat1,
  [598] = 3,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      aux_sym__arg_list_repeat1,
  [608] = 1,
    ACTIONS(161), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [613] = 1,
    ACTIONS(163), 1,
      anon_sym_LPAREN,
  [617] = 1,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
  [621] = 1,
    ACTIONS(167), 1,
      sym_identifier,
  [625] = 1,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
  [629] = 1,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
  [633] = 1,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
  [637] = 1,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
  [641] = 1,
    ACTIONS(177), 1,
      sym_identifier,
  [645] = 1,
    ACTIONS(179), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 32,
  [SMALL_STATE(7)] = 64,
  [SMALL_STATE(8)] = 96,
  [SMALL_STATE(9)] = 128,
  [SMALL_STATE(10)] = 158,
  [SMALL_STATE(11)] = 190,
  [SMALL_STATE(12)] = 220,
  [SMALL_STATE(13)] = 249,
  [SMALL_STATE(14)] = 263,
  [SMALL_STATE(15)] = 277,
  [SMALL_STATE(16)] = 291,
  [SMALL_STATE(17)] = 305,
  [SMALL_STATE(18)] = 319,
  [SMALL_STATE(19)] = 333,
  [SMALL_STATE(20)] = 347,
  [SMALL_STATE(21)] = 361,
  [SMALL_STATE(22)] = 375,
  [SMALL_STATE(23)] = 389,
  [SMALL_STATE(24)] = 403,
  [SMALL_STATE(25)] = 417,
  [SMALL_STATE(26)] = 431,
  [SMALL_STATE(27)] = 445,
  [SMALL_STATE(28)] = 459,
  [SMALL_STATE(29)] = 474,
  [SMALL_STATE(30)] = 489,
  [SMALL_STATE(31)] = 504,
  [SMALL_STATE(32)] = 519,
  [SMALL_STATE(33)] = 534,
  [SMALL_STATE(34)] = 549,
  [SMALL_STATE(35)] = 564,
  [SMALL_STATE(36)] = 571,
  [SMALL_STATE(37)] = 578,
  [SMALL_STATE(38)] = 588,
  [SMALL_STATE(39)] = 598,
  [SMALL_STATE(40)] = 608,
  [SMALL_STATE(41)] = 613,
  [SMALL_STATE(42)] = 617,
  [SMALL_STATE(43)] = 621,
  [SMALL_STATE(44)] = 625,
  [SMALL_STATE(45)] = 629,
  [SMALL_STATE(46)] = 633,
  [SMALL_STATE(47)] = 637,
  [SMALL_STATE(48)] = 641,
  [SMALL_STATE(49)] = 645,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_comment, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 1),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 2),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 2),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_call, 3, 0, 3),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_call, 3, 0, 3),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 5),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 5),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_call, 4, 0, 6),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_call, 4, 0, 6),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_comment, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1, 0, 0),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_comment_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arg_list, 2, 0, 7),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__arg_list_repeat1, 2, 0, 9),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__arg_list_repeat1, 2, 0, 9), SHIFT_REPEAT(12),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arg_list, 1, 0, 4),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__arg_list_repeat1, 2, 0, 8),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [169] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_azadi(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "azadi",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
