/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_text_token1 = 1,
  sym_arg_text = 2,
  sym_escaped_special = 3,
  anon_sym_PERCENT_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_LPAREN = 6,
  sym_macro_name = 7,
  anon_sym_COMMA = 8,
  sym_block_open = 9,
  sym_block_close = 10,
  sym_verbatim_open = 11,
  sym_verbatim_close = 12,
  sym_verbatim_text = 13,
  sym_line_comment = 14,
  anon_sym_PERCENT_SLASH_STAR = 15,
  aux_sym_block_comment_token1 = 16,
  anon_sym_PERCENT_STAR_SLASH = 17,
  sym_identifier = 18,
  sym_source_file = 19,
  sym__node = 20,
  sym__arg_node = 21,
  sym_text = 22,
  sym_variable = 23,
  sym_macro_call = 24,
  sym__arg_list = 25,
  sym_argument = 26,
  sym_block = 27,
  sym_verbatim_block = 28,
  sym_block_comment = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym__arg_list_repeat1 = 31,
  aux_sym_argument_repeat1 = 32,
  aux_sym_verbatim_block_repeat1 = 33,
  aux_sym_block_comment_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_text_token1] = "text_token1",
  [sym_arg_text] = "arg_text",
  [sym_escaped_special] = "escaped_special",
  [anon_sym_PERCENT_LPAREN] = "%(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LPAREN] = "(",
  [sym_macro_name] = "macro_name",
  [anon_sym_COMMA] = ",",
  [sym_block_open] = "block_open",
  [sym_block_close] = "block_close",
  [sym_verbatim_open] = "verbatim_open",
  [sym_verbatim_close] = "verbatim_close",
  [sym_verbatim_text] = "verbatim_text",
  [sym_line_comment] = "line_comment",
  [anon_sym_PERCENT_SLASH_STAR] = "%/*",
  [aux_sym_block_comment_token1] = "block_comment_token1",
  [anon_sym_PERCENT_STAR_SLASH] = "%*/",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__node] = "_node",
  [sym__arg_node] = "_arg_node",
  [sym_text] = "text",
  [sym_variable] = "variable",
  [sym_macro_call] = "macro_call",
  [sym__arg_list] = "_arg_list",
  [sym_argument] = "argument",
  [sym_block] = "block",
  [sym_verbatim_block] = "verbatim_block",
  [sym_block_comment] = "block_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__arg_list_repeat1] = "_arg_list_repeat1",
  [aux_sym_argument_repeat1] = "argument_repeat1",
  [aux_sym_verbatim_block_repeat1] = "verbatim_block_repeat1",
  [aux_sym_block_comment_repeat1] = "block_comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_text_token1] = aux_sym_text_token1,
  [sym_arg_text] = sym_arg_text,
  [sym_escaped_special] = sym_escaped_special,
  [anon_sym_PERCENT_LPAREN] = anon_sym_PERCENT_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [sym_macro_name] = sym_macro_name,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_block_open] = sym_block_open,
  [sym_block_close] = sym_block_close,
  [sym_verbatim_open] = sym_verbatim_open,
  [sym_verbatim_close] = sym_verbatim_close,
  [sym_verbatim_text] = sym_verbatim_text,
  [sym_line_comment] = sym_line_comment,
  [anon_sym_PERCENT_SLASH_STAR] = anon_sym_PERCENT_SLASH_STAR,
  [aux_sym_block_comment_token1] = aux_sym_block_comment_token1,
  [anon_sym_PERCENT_STAR_SLASH] = anon_sym_PERCENT_STAR_SLASH,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__node] = sym__node,
  [sym__arg_node] = sym__arg_node,
  [sym_text] = sym_text,
  [sym_variable] = sym_variable,
  [sym_macro_call] = sym_macro_call,
  [sym__arg_list] = sym__arg_list,
  [sym_argument] = sym_argument,
  [sym_block] = sym_block,
  [sym_verbatim_block] = sym_verbatim_block,
  [sym_block_comment] = sym_block_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__arg_list_repeat1] = aux_sym__arg_list_repeat1,
  [aux_sym_argument_repeat1] = aux_sym_argument_repeat1,
  [aux_sym_verbatim_block_repeat1] = aux_sym_verbatim_block_repeat1,
  [aux_sym_block_comment_repeat1] = aux_sym_block_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_text_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_arg_text] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped_special] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_macro_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_block_open] = {
    .visible = true,
    .named = true,
  },
  [sym_block_close] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_open] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_close] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_text] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym__arg_node] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_call] = {
    .visible = true,
    .named = true,
  },
  [sym__arg_list] = {
    .visible = false,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__arg_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_verbatim_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg = 1,
  field_close = 2,
  field_name = 3,
  field_open = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg] = "arg",
  [field_close] = "close",
  [field_name] = "name",
  [field_open] = "open",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_close, 1},
    {field_open, 0},
  [2] =
    {field_name, 1},
  [3] =
    {field_name, 0},
  [4] =
    {field_arg, 0},
  [5] =
    {field_close, 2},
    {field_open, 0},
  [7] =
    {field_arg, 2, .inherited = true},
    {field_name, 0},
  [9] =
    {field_arg, 0},
    {field_arg, 1, .inherited = true},
  [11] =
    {field_arg, 1},
  [12] =
    {field_arg, 0, .inherited = true},
    {field_arg, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 7,
  [11] = 6,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 13,
  [24] = 16,
  [25] = 18,
  [26] = 19,
  [27] = 22,
  [28] = 15,
  [29] = 17,
  [30] = 20,
  [31] = 21,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 34,
  [36] = 33,
  [37] = 33,
  [38] = 34,
  [39] = 39,
  [40] = 40,
  [41] = 40,
  [42] = 42,
  [43] = 40,
  [44] = 42,
  [45] = 42,
  [46] = 21,
  [47] = 17,
  [48] = 15,
  [49] = 49,
  [50] = 20,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 57,
  [59] = 54,
  [60] = 60,
  [61] = 60,
  [62] = 56,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '%') ADVANCE(1);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == ',') ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '#', 34,
        '%', 18,
        '(', 19,
        '*', 11,
        '-', 37,
        '/', 9,
        '[', 28,
        ']', 29,
        '{', 26,
        '}', 27,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '#', 34,
        '%', 18,
        '(', 19,
        '-', 10,
        '/', 9,
        '[', 28,
        '{', 26,
        '}', 27,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '%') ADVANCE(18);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == '{') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(3);
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == ',') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == '%') ADVANCE(7);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == '%') ADVANCE(31);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(35);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(35);
      if (lookahead == '/') ADVANCE(34);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 12:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '%') ADVANCE(2);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_arg_text);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '%' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_arg_text);
      if (lookahead != 0 &&
          lookahead != '%' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_escaped_special);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_PERCENT_LPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == ']') ADVANCE(29);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead == '}') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead == '}') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == '{') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_block_open);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_block_close);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_verbatim_open);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_verbatim_close);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_verbatim_text);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_verbatim_text);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == ']') ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_verbatim_text);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == ']') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_verbatim_text);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PERCENT_SLASH_STAR);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_block_comment_token1);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_block_comment_token1);
      if (lookahead == '-') ADVANCE(34);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PERCENT_STAR_SLASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 13},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 13},
  [6] = {.lex_state = 13},
  [7] = {.lex_state = 13},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 13},
  [11] = {.lex_state = 13},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 13},
  [14] = {.lex_state = 13},
  [15] = {.lex_state = 13},
  [16] = {.lex_state = 13},
  [17] = {.lex_state = 13},
  [18] = {.lex_state = 13},
  [19] = {.lex_state = 13},
  [20] = {.lex_state = 13},
  [21] = {.lex_state = 13},
  [22] = {.lex_state = 13},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 12},
  [61] = {.lex_state = 12},
  [62] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_arg_text] = ACTIONS(1),
    [sym_escaped_special] = ACTIONS(1),
    [anon_sym_PERCENT_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [sym_macro_name] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_block_open] = ACTIONS(1),
    [sym_block_close] = ACTIONS(1),
    [sym_verbatim_open] = ACTIONS(1),
    [sym_verbatim_close] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [anon_sym_PERCENT_SLASH_STAR] = ACTIONS(1),
    [aux_sym_block_comment_token1] = ACTIONS(1),
    [anon_sym_PERCENT_STAR_SLASH] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(55),
    [sym__node] = STATE(5),
    [sym_text] = STATE(5),
    [sym_variable] = STATE(5),
    [sym_macro_call] = STATE(5),
    [sym_block] = STATE(5),
    [sym_verbatim_block] = STATE(5),
    [sym_block_comment] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_text_token1] = ACTIONS(5),
    [sym_escaped_special] = ACTIONS(7),
    [anon_sym_PERCENT_LPAREN] = ACTIONS(9),
    [sym_macro_name] = ACTIONS(11),
    [sym_block_open] = ACTIONS(13),
    [sym_verbatim_open] = ACTIONS(15),
    [sym_line_comment] = ACTIONS(7),
    [anon_sym_PERCENT_SLASH_STAR] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym__node] = STATE(2),
    [sym_text] = STATE(2),
    [sym_variable] = STATE(2),
    [sym_macro_call] = STATE(2),
    [sym_block] = STATE(2),
    [sym_verbatim_block] = STATE(2),
    [sym_block_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(19),
    [aux_sym_text_token1] = ACTIONS(21),
    [sym_escaped_special] = ACTIONS(24),
    [anon_sym_PERCENT_LPAREN] = ACTIONS(27),
    [sym_macro_name] = ACTIONS(30),
    [sym_block_open] = ACTIONS(33),
    [sym_block_close] = ACTIONS(19),
    [sym_verbatim_open] = ACTIONS(36),
    [sym_line_comment] = ACTIONS(24),
    [anon_sym_PERCENT_SLASH_STAR] = ACTIONS(39),
  },
  [STATE(3)] = {
    [sym__arg_node] = STATE(8),
    [sym_variable] = STATE(8),
    [sym_macro_call] = STATE(8),
    [sym__arg_list] = STATE(54),
    [sym_argument] = STATE(51),
    [sym_block] = STATE(8),
    [sym_verbatim_block] = STATE(8),
    [sym_block_comment] = STATE(8),
    [aux_sym_argument_repeat1] = STATE(8),
    [sym_arg_text] = ACTIONS(42),
    [sym_escaped_special] = ACTIONS(42),
    [anon_sym_PERCENT_LPAREN] = ACTIONS(44),
    [anon_sym_RPAREN] = ACTIONS(46),
    [sym_macro_name] = ACTIONS(48),
    [sym_block_open] = ACTIONS(50),
    [sym_verbatim_open] = ACTIONS(52),
    [sym_line_comment] = ACTIONS(42),
    [anon_sym_PERCENT_SLASH_STAR] = ACTIONS(54),
  },
  [STATE(4)] = {
    [sym__arg_node] = STATE(8),
    [sym_variable] = STATE(8),
    [sym_macro_call] = STATE(8),
    [sym__arg_list] = STATE(59),
    [sym_argument] = STATE(51),
    [sym_block] = STATE(8),
    [sym_verbatim_block] = STATE(8),
    [sym_block_comment] = STATE(8),
    [aux_sym_argument_repeat1] = STATE(8),
    [sym_arg_text] = ACTIONS(42),
    [sym_escaped_special] = ACTIONS(42),
    [anon_sym_PERCENT_LPAREN] = ACTIONS(44),
    [anon_sym_RPAREN] = ACTIONS(56),
    [sym_macro_name] = ACTIONS(48),
    [sym_block_open] = ACTIONS(50),
    [sym_verbatim_open] = ACTIONS(52),
    [sym_line_comment] = ACTIONS(42),
    [anon_sym_PERCENT_SLASH_STAR] = ACTIONS(54),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(5), 1,
      aux_sym_text_token1,
    ACTIONS(9), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(11), 1,
      sym_macro_name,
    ACTIONS(13), 1,
      sym_block_open,
    ACTIONS(15), 1,
      sym_verbatim_open,
    ACTIONS(17), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 2,
      sym_escaped_special,
      sym_line_comment,
    STATE(2), 8,
      sym__node,
      sym_text,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_verbatim_block,
      sym_block_comment,
      aux_sym_source_file_repeat1,
  [36] = 9,
    ACTIONS(5), 1,
      aux_sym_text_token1,
    ACTIONS(9), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(11), 1,
      sym_macro_name,
    ACTIONS(13), 1,
      sym_block_open,
    ACTIONS(15), 1,
      sym_verbatim_open,
    ACTIONS(17), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(62), 1,
      sym_block_close,
    ACTIONS(60), 2,
      sym_escaped_special,
      sym_line_comment,
    STATE(2), 8,
      sym__node,
      sym_text,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_verbatim_block,
      sym_block_comment,
      aux_sym_source_file_repeat1,
  [72] = 9,
    ACTIONS(5), 1,
      aux_sym_text_token1,
    ACTIONS(9), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(11), 1,
      sym_macro_name,
    ACTIONS(13), 1,
      sym_block_open,
    ACTIONS(15), 1,
      sym_verbatim_open,
    ACTIONS(17), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(66), 1,
      sym_block_close,
    ACTIONS(64), 2,
      sym_escaped_special,
      sym_line_comment,
    STATE(6), 8,
      sym__node,
      sym_text,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_verbatim_block,
      sym_block_comment,
      aux_sym_source_file_repeat1,
  [108] = 8,
    ACTIONS(44), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(48), 1,
      sym_macro_name,
    ACTIONS(50), 1,
      sym_block_open,
    ACTIONS(52), 1,
      sym_verbatim_open,
    ACTIONS(54), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(70), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(68), 3,
      sym_arg_text,
      sym_escaped_special,
      sym_line_comment,
    STATE(9), 7,
      sym__arg_node,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_verbatim_block,
      sym_block_comment,
      aux_sym_argument_repeat1,
  [142] = 8,
    ACTIONS(75), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(80), 1,
      sym_macro_name,
    ACTIONS(83), 1,
      sym_block_open,
    ACTIONS(86), 1,
      sym_verbatim_open,
    ACTIONS(89), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(78), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(72), 3,
      sym_arg_text,
      sym_escaped_special,
      sym_line_comment,
    STATE(9), 7,
      sym__arg_node,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_verbatim_block,
      sym_block_comment,
      aux_sym_argument_repeat1,
  [176] = 9,
    ACTIONS(5), 1,
      aux_sym_text_token1,
    ACTIONS(9), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(11), 1,
      sym_macro_name,
    ACTIONS(13), 1,
      sym_block_open,
    ACTIONS(15), 1,
      sym_verbatim_open,
    ACTIONS(17), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(94), 1,
      sym_block_close,
    ACTIONS(92), 2,
      sym_escaped_special,
      sym_line_comment,
    STATE(11), 8,
      sym__node,
      sym_text,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_verbatim_block,
      sym_block_comment,
      aux_sym_source_file_repeat1,
  [212] = 9,
    ACTIONS(5), 1,
      aux_sym_text_token1,
    ACTIONS(9), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(11), 1,
      sym_macro_name,
    ACTIONS(13), 1,
      sym_block_open,
    ACTIONS(15), 1,
      sym_verbatim_open,
    ACTIONS(17), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(96), 1,
      sym_block_close,
    ACTIONS(60), 2,
      sym_escaped_special,
      sym_line_comment,
    STATE(2), 8,
      sym__node,
      sym_text,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_verbatim_block,
      sym_block_comment,
      aux_sym_source_file_repeat1,
  [248] = 8,
    ACTIONS(44), 1,
      anon_sym_PERCENT_LPAREN,
    ACTIONS(48), 1,
      sym_macro_name,
    ACTIONS(50), 1,
      sym_block_open,
    ACTIONS(52), 1,
      sym_verbatim_open,
    ACTIONS(54), 1,
      anon_sym_PERCENT_SLASH_STAR,
    STATE(53), 1,
      sym_argument,
    ACTIONS(42), 3,
      sym_arg_text,
      sym_escaped_special,
      sym_line_comment,
    STATE(8), 7,
      sym__arg_node,
      sym_variable,
      sym_macro_call,
      sym_block,
      sym_verbatim_block,
      sym_block_comment,
      aux_sym_argument_repeat1,
  [281] = 2,
    ACTIONS(100), 1,
      sym_macro_name,
    ACTIONS(98), 9,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [296] = 2,
    ACTIONS(104), 1,
      sym_macro_name,
    ACTIONS(102), 9,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [311] = 2,
    ACTIONS(108), 1,
      sym_macro_name,
    ACTIONS(106), 9,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [326] = 2,
    ACTIONS(112), 1,
      sym_macro_name,
    ACTIONS(110), 9,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [341] = 2,
    ACTIONS(116), 1,
      sym_macro_name,
    ACTIONS(114), 9,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [356] = 2,
    ACTIONS(120), 1,
      sym_macro_name,
    ACTIONS(118), 9,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [371] = 2,
    ACTIONS(124), 1,
      sym_macro_name,
    ACTIONS(122), 9,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [386] = 2,
    ACTIONS(128), 1,
      sym_macro_name,
    ACTIONS(126), 9,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [401] = 2,
    ACTIONS(132), 1,
      sym_macro_name,
    ACTIONS(130), 9,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [416] = 2,
    ACTIONS(136), 1,
      sym_macro_name,
    ACTIONS(134), 9,
      ts_builtin_sym_end,
      aux_sym_text_token1,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      sym_block_open,
      sym_block_close,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [431] = 2,
    ACTIONS(100), 1,
      sym_macro_name,
    ACTIONS(98), 9,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [446] = 2,
    ACTIONS(112), 1,
      sym_macro_name,
    ACTIONS(110), 9,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [461] = 2,
    ACTIONS(120), 1,
      sym_macro_name,
    ACTIONS(118), 9,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [476] = 2,
    ACTIONS(124), 1,
      sym_macro_name,
    ACTIONS(122), 9,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [491] = 2,
    ACTIONS(136), 1,
      sym_macro_name,
    ACTIONS(134), 9,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [506] = 2,
    ACTIONS(108), 1,
      sym_macro_name,
    ACTIONS(106), 9,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [521] = 2,
    ACTIONS(116), 1,
      sym_macro_name,
    ACTIONS(114), 9,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [536] = 2,
    ACTIONS(128), 1,
      sym_macro_name,
    ACTIONS(126), 9,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [551] = 2,
    ACTIONS(132), 1,
      sym_macro_name,
    ACTIONS(130), 9,
      sym_arg_text,
      sym_escaped_special,
      anon_sym_PERCENT_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_block_open,
      sym_verbatim_open,
      sym_line_comment,
      anon_sym_PERCENT_SLASH_STAR,
  [566] = 4,
    ACTIONS(141), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(144), 1,
      anon_sym_PERCENT_STAR_SLASH,
    ACTIONS(138), 2,
      aux_sym_text_token1,
      aux_sym_block_comment_token1,
    STATE(32), 2,
      sym_block_comment,
      aux_sym_block_comment_repeat1,
  [581] = 4,
    ACTIONS(148), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(150), 1,
      anon_sym_PERCENT_STAR_SLASH,
    ACTIONS(146), 2,
      aux_sym_text_token1,
      aux_sym_block_comment_token1,
    STATE(34), 2,
      sym_block_comment,
      aux_sym_block_comment_repeat1,
  [596] = 4,
    ACTIONS(148), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(154), 1,
      anon_sym_PERCENT_STAR_SLASH,
    ACTIONS(152), 2,
      aux_sym_text_token1,
      aux_sym_block_comment_token1,
    STATE(32), 2,
      sym_block_comment,
      aux_sym_block_comment_repeat1,
  [611] = 4,
    ACTIONS(148), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(156), 1,
      anon_sym_PERCENT_STAR_SLASH,
    ACTIONS(152), 2,
      aux_sym_text_token1,
      aux_sym_block_comment_token1,
    STATE(32), 2,
      sym_block_comment,
      aux_sym_block_comment_repeat1,
  [626] = 4,
    ACTIONS(148), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(160), 1,
      anon_sym_PERCENT_STAR_SLASH,
    ACTIONS(158), 2,
      aux_sym_text_token1,
      aux_sym_block_comment_token1,
    STATE(35), 2,
      sym_block_comment,
      aux_sym_block_comment_repeat1,
  [641] = 4,
    ACTIONS(148), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(164), 1,
      anon_sym_PERCENT_STAR_SLASH,
    ACTIONS(162), 2,
      aux_sym_text_token1,
      aux_sym_block_comment_token1,
    STATE(38), 2,
      sym_block_comment,
      aux_sym_block_comment_repeat1,
  [656] = 4,
    ACTIONS(148), 1,
      anon_sym_PERCENT_SLASH_STAR,
    ACTIONS(166), 1,
      anon_sym_PERCENT_STAR_SLASH,
    ACTIONS(152), 2,
      aux_sym_text_token1,
      aux_sym_block_comment_token1,
    STATE(32), 2,
      sym_block_comment,
      aux_sym_block_comment_repeat1,
  [671] = 4,
    ACTIONS(168), 1,
      sym_verbatim_open,
    ACTIONS(171), 1,
      sym_verbatim_close,
    ACTIONS(173), 1,
      sym_verbatim_text,
    STATE(39), 2,
      sym_verbatim_block,
      aux_sym_verbatim_block_repeat1,
  [685] = 4,
    ACTIONS(176), 1,
      sym_verbatim_open,
    ACTIONS(178), 1,
      sym_verbatim_close,
    ACTIONS(180), 1,
      sym_verbatim_text,
    STATE(39), 2,
      sym_verbatim_block,
      aux_sym_verbatim_block_repeat1,
  [699] = 4,
    ACTIONS(176), 1,
      sym_verbatim_open,
    ACTIONS(180), 1,
      sym_verbatim_text,
    ACTIONS(182), 1,
      sym_verbatim_close,
    STATE(39), 2,
      sym_verbatim_block,
      aux_sym_verbatim_block_repeat1,
  [713] = 4,
    ACTIONS(176), 1,
      sym_verbatim_open,
    ACTIONS(184), 1,
      sym_verbatim_close,
    ACTIONS(186), 1,
      sym_verbatim_text,
    STATE(40), 2,
      sym_verbatim_block,
      aux_sym_verbatim_block_repeat1,
  [727] = 4,
    ACTIONS(176), 1,
      sym_verbatim_open,
    ACTIONS(180), 1,
      sym_verbatim_text,
    ACTIONS(188), 1,
      sym_verbatim_close,
    STATE(39), 2,
      sym_verbatim_block,
      aux_sym_verbatim_block_repeat1,
  [741] = 4,
    ACTIONS(176), 1,
      sym_verbatim_open,
    ACTIONS(190), 1,
      sym_verbatim_close,
    ACTIONS(192), 1,
      sym_verbatim_text,
    STATE(41), 2,
      sym_verbatim_block,
      aux_sym_verbatim_block_repeat1,
  [755] = 4,
    ACTIONS(176), 1,
      sym_verbatim_open,
    ACTIONS(194), 1,
      sym_verbatim_close,
    ACTIONS(196), 1,
      sym_verbatim_text,
    STATE(43), 2,
      sym_verbatim_block,
      aux_sym_verbatim_block_repeat1,
  [769] = 1,
    ACTIONS(130), 4,
      aux_sym_text_token1,
      anon_sym_PERCENT_SLASH_STAR,
      aux_sym_block_comment_token1,
      anon_sym_PERCENT_STAR_SLASH,
  [776] = 1,
    ACTIONS(114), 4,
      aux_sym_text_token1,
      anon_sym_PERCENT_SLASH_STAR,
      aux_sym_block_comment_token1,
      anon_sym_PERCENT_STAR_SLASH,
  [783] = 2,
    ACTIONS(108), 1,
      sym_verbatim_text,
    ACTIONS(106), 2,
      sym_verbatim_open,
      sym_verbatim_close,
  [791] = 3,
    ACTIONS(198), 1,
      anon_sym_RPAREN,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym__arg_list_repeat1,
  [801] = 2,
    ACTIONS(128), 1,
      sym_verbatim_text,
    ACTIONS(126), 2,
      sym_verbatim_open,
      sym_verbatim_close,
  [809] = 3,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
    ACTIONS(205), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym__arg_list_repeat1,
  [819] = 3,
    ACTIONS(205), 1,
      anon_sym_COMMA,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym__arg_list_repeat1,
  [829] = 1,
    ACTIONS(209), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [834] = 1,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
  [838] = 1,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
  [842] = 1,
    ACTIONS(215), 1,
      anon_sym_LPAREN,
  [846] = 1,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
  [850] = 1,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
  [854] = 1,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
  [858] = 1,
    ACTIONS(223), 1,
      sym_identifier,
  [862] = 1,
    ACTIONS(225), 1,
      sym_identifier,
  [866] = 1,
    ACTIONS(227), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 36,
  [SMALL_STATE(7)] = 72,
  [SMALL_STATE(8)] = 108,
  [SMALL_STATE(9)] = 142,
  [SMALL_STATE(10)] = 176,
  [SMALL_STATE(11)] = 212,
  [SMALL_STATE(12)] = 248,
  [SMALL_STATE(13)] = 281,
  [SMALL_STATE(14)] = 296,
  [SMALL_STATE(15)] = 311,
  [SMALL_STATE(16)] = 326,
  [SMALL_STATE(17)] = 341,
  [SMALL_STATE(18)] = 356,
  [SMALL_STATE(19)] = 371,
  [SMALL_STATE(20)] = 386,
  [SMALL_STATE(21)] = 401,
  [SMALL_STATE(22)] = 416,
  [SMALL_STATE(23)] = 431,
  [SMALL_STATE(24)] = 446,
  [SMALL_STATE(25)] = 461,
  [SMALL_STATE(26)] = 476,
  [SMALL_STATE(27)] = 491,
  [SMALL_STATE(28)] = 506,
  [SMALL_STATE(29)] = 521,
  [SMALL_STATE(30)] = 536,
  [SMALL_STATE(31)] = 551,
  [SMALL_STATE(32)] = 566,
  [SMALL_STATE(33)] = 581,
  [SMALL_STATE(34)] = 596,
  [SMALL_STATE(35)] = 611,
  [SMALL_STATE(36)] = 626,
  [SMALL_STATE(37)] = 641,
  [SMALL_STATE(38)] = 656,
  [SMALL_STATE(39)] = 671,
  [SMALL_STATE(40)] = 685,
  [SMALL_STATE(41)] = 699,
  [SMALL_STATE(42)] = 713,
  [SMALL_STATE(43)] = 727,
  [SMALL_STATE(44)] = 741,
  [SMALL_STATE(45)] = 755,
  [SMALL_STATE(46)] = 769,
  [SMALL_STATE(47)] = 776,
  [SMALL_STATE(48)] = 783,
  [SMALL_STATE(49)] = 791,
  [SMALL_STATE(50)] = 801,
  [SMALL_STATE(51)] = 809,
  [SMALL_STATE(52)] = 819,
  [SMALL_STATE(53)] = 829,
  [SMALL_STATE(54)] = 834,
  [SMALL_STATE(55)] = 838,
  [SMALL_STATE(56)] = 842,
  [SMALL_STATE(57)] = 846,
  [SMALL_STATE(58)] = 850,
  [SMALL_STATE(59)] = 854,
  [SMALL_STATE(60)] = 858,
  [SMALL_STATE(61)] = 862,
  [SMALL_STATE(62)] = 866,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 1),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 1),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_block, 2, 0, 1),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_block, 2, 0, 1),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 2),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 2),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_comment, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_call, 3, 0, 3),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_call, 3, 0, 3),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 5),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 5),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_block, 3, 0, 5),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_block, 3, 0, 5),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_comment, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_call, 4, 0, 6),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_call, 4, 0, 6),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_comment_repeat1, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_verbatim_block_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_verbatim_block_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_verbatim_block_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__arg_list_repeat1, 2, 0, 9),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__arg_list_repeat1, 2, 0, 9), SHIFT_REPEAT(12),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arg_list, 1, 0, 4),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arg_list, 2, 0, 7),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__arg_list_repeat1, 2, 0, 8),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [213] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_weaveback(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "weaveback",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
